### ISSUE TITLE
Attendance tracking

### ISSUE THREAD

**Issue by busyboxhere** [busyboxhere/hrm#11]
This is  the root issue for Attendance feature implementation.

In this we will 

- [ ] Design the schema for Attendance feature
- [ ] Create Entity classes for Attendance feature
- [ ] Create Repository Classes for Attendance feature
- [ ] Create Service interfaces and IMPLs for Attendance feature
- [ ] Create Exception Classes and Global Exception Handler for Attendance feature
- [ ] Create DTO classes for Attendance feature
- [ ] Create Controllers for Attendance feature
- [ ] Add Testing for Attendance feature
